### ISSUE TITLE
Unnable to activate the plugin

### ISSUE THREAD

**Issue by Gilsaaa** [shun126/DrawLots#3]
I'm currently using Unreal Engine 5.4.4, and after adding the plugin and enabling it, after the restart I get the error "Engine modules are out of date, and cannot be compiled while the engine is running. Please build through your IDE" . Now, I dont know if this is an issue caused by something I dont know, since its my first time installing a thirdparty plugin, or an issue with the engine. Thanks.

**Comment by shun126** [comment]
Sorry for the inconvenience.

**Comment by shun126** [comment]
What version of Visual Studio do you have?
Version 17.12.0 fails to build due to a weakness in the NuGet package.
I am looking for a solution.

バージョン17.12.0ではNuGetパッケージの虚弱性によりビルドが失敗しています。
解決方法を探しています。

![image](https://github.com/user-attachments/assets/77f8d095-f5a8-456f-8ef0-ae86b5808e5c)

**Comment by Gilsaaa** [comment]
Hey, after installing the plugin directly from fab, its working perfectly. Also, yeah that's the visual studio version I had installed, maybe that's why I couldn't install it manually. Thanks for the help.

**Comment by shun126** [comment]
I am relieved that it worked safely.
無事に動作して安心しました。
